#!/bin/bash

set -e

mkdir -p deps
cd deps

# Datomic
[[ -d datomic ]] && rm -rf datomic
datomic_release_url="https://my.datomic.com/downloads/free/0.9.4384"
echo "=> Fetching Datomic Free from $datomic_release_url..."
curl -O -L -J -s $datomic_release_url
datomic_file=$(ls *.zip | tail -1)
unzip $datomic_file
mv $(basename $datomic_file .zip) datomic
rm $datomic_file

# Codeq
[[ -d codeq ]] && rm -rf codeq
echo "=> Fetching codeq from GitHub.."
git clone https://github.com/Datomic/codeq.git
cd codeq
echo "=> Building codeq jar..."
lein uberjar
