#!/bin/bash

set -e

mkdir -p deps
cd deps

# Datomic
[[ -d datomic ]] && rm -rf datomic
datomic_release_url="http://downloads.datomic.com/0.8.4143/datomic-free-0.8.4143.zip"
echo "=> Fetching Datomic Free from $datomic_release_url..."
curl -O -s $datomic_release_url
unzip $(basename $datomic_release_url .zip)
mv $(basename $datomic_release_url .zip) datomic
rm $(basename $datomic_release_url)

# Codeq
[[ -d codeq ]] && rm -rf codeq
echo "=> Fetching catamorphic's codeq fork from GitHub.."
git clone https://github.com/catamorphic/codeq-catamorphic
cd codeq
echo "=> Building codeq jar..."
lein uberjar
